# Generated by Django 4.1.5 on 2023-01-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact1", models.CharField(max_length=150)),
                ("operation", models.CharField(max_length=150)),
                ("fact2", models.CharField(max_length=150)),
                ("conclude", models.CharField(max_length=150)),
            ],
        ),
    ]
