# Generated by Django 4.1.5 on 2023-01-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inference_engine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="fact2",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="operation",
        ),
    ]
