# Generated by Django 4.1.5 on 2023-01-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference_engine", "0002_remove_rule_fact2_remove_rule_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="fact2",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="fact3",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="operator1",
            field=models.CharField(
                choices=[("and", "AND"), ("or", "OR")], max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="operator2",
            field=models.CharField(
                choices=[("and", "AND"), ("or", "OR")], max_length=3, null=True
            ),
        ),
    ]
