# Generated by Django 4.1.5 on 2023-01-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inference_engine",
            "0003_rule_fact2_rule_fact3_rule_operator1_rule_operator2",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="fact2",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="fact3",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="operator1",
            field=models.CharField(
                blank=True,
                choices=[("and", "AND"), ("or", "OR")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="operator2",
            field=models.CharField(
                blank=True,
                choices=[("and", "AND"), ("or", "OR")],
                max_length=3,
                null=True,
            ),
        ),
    ]
