# Generated by Django 4.1.5 on 2023-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference_engine", "0004_alter_rule_fact2_alter_rule_fact3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="operator1",
            field=models.CharField(
                blank=True,
                choices=[("AND", "AND"), ("OR", "OR")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="operator2",
            field=models.CharField(
                blank=True,
                choices=[("AND", "AND"), ("OR", "OR")],
                max_length=3,
                null=True,
            ),
        ),
    ]
