# Generated by Django 4.1.5 on 2023-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference_engine", "0008_rule_fact1_prefix_rule_fact2_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="fact1_prefix",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="fact2_prefix",
            field=models.BooleanField(default=True),
        ),
    ]
